### ISSUE TITLE
Import packages

### ISSUE THREAD

**Issue by kylekyle** [nbgallery/ipydeps#1]
`ipydeps` should import the packages the user requested once they are installed.

**Comment by billallen256** [comment]
So I've been thinking about this for a few days now, and there are a few serious gotchas that require further consideration before deciding to implement this...

First there's the problem of getting the imported package into the calling script's namespace.  This seems do-able though thanks to Python's introspection.  Unfortunately, it's far from the only problem.

Package names don't always align with the actual import name.  For example, the beautifulsoup4 package for parsing HTML is imported with `import bs4`.  If we want to make this work automagically, we'd have to create (and maintain!) a mapping of package names to import names.  We can't possibly do this for all packages, and if it doesn't "just work" for everything, I'd honestly rather not do it.

Someone also suggested having `import` automagically install a package if it isn't already there.  Again, this would have the problem of creating and maintaining the mappings from import names to package names.

There's also the problem of import's `as` keyword, which often has idiomatic consequences.  For example, it is idiomatic to say `import numpy as np`.  What should we do here?  Ignore the idiom and just `import numpy`?  Finding and supporting the idioms for the really popular packages would be fairly easy, but it's yet another thing to maintain, and it would be quite difficult for the more niche packages.

Import also has the `from` keyword, which is extremely popular with a lot of packages, not to mention more efficient since it allows only the useful portion of the package to take up resources.  For example, `from sklearn.cluster import KMeans`.  I don't even know how we'd support that.

Which brings us to the subject of subpackages.  If we ipydeps.pip('sklearn'), how would we know to `import sklearn.cluster`?

Ok, sorry for the whole bag of snakes (er, pythons).  I'm open to elegant suggestions.

**Comment by kylekyle** [comment]
I would take the same approach as [bundler](http://bundler.io), which assumes that package names line up with import names. When they don't, you can specify the import, for example:

``` python
ipydeps.pip('beautifulsoup4', package='bs4')
ipydeps.pip('numpy', import_as='np')
ipydeps.pip('sklearn', package=false)
```

**Comment by billallen256** [comment]
Interesting, but how is this better than a normal import on its own line (and all the flexibility that entails)?

**Comment by kylekyle** [comment]
Because most import names are the same as thier package names, so it will just work. This is just a mechanism for dealing with exceptions.

**Comment by echowhisky** [comment]
If it is going to be an option to auto import after install of a package, it shouldn't be the default. It seems like it would be easier, especially for ease of use with notebooks not developed originally with ipydeps in mind or for going back and forth, to not have to rewrite all of the import statements.

**Comment by kylekyle** [comment]
I personally think they should load by default. You don't have to rewrite existing import statements since importing twice doesn't generate an error. Going forward it halves the amount of code needed to import. Importing by default also keeps us consistent with [other languages](http://bundler.io).

**Comment by billallen256** [comment]
I'm not sure this makes sense any more with the way most people use `ipydeps.pip(['list', 'of', 'packages'])`.  I also haven't heard requests for this feature through other channels, but I'll admit most users aren't visionaries like @kylekyle :-)
