### ISSUE TITLE
package install order not maintained

### ISSUE THREAD

**Issue by echowhisky** [nbgallery/ipydeps#22]
When using something like  
```python
ipydeps.pip('package1 beta_package somethingElse anotherPackage')
```
or
```python
ipydeps.pip(['anotherPackage', 'somethingElse','beta_package', 'package1', 'anotherPackage'])
```
the packages will be installed in an unpredictable order because the .pip() function starts by passing its argument through `_pkg_name_list(x)` which (among its transforms) turns everything into a set before turning it back into a list. Sets are, of course, unordered in Python. The code actually transforms it into a set in `_pkg_name_list()`, and then takes the list result and turns it into a set again, and then passes the set object to the `_subtract_installed()` function which starts by turning it into a set again, just in case any duplicates have snuck through the previous ones somehow. 

I have started on some replacement code to submit as a pull request, but first wanted to understand if there was a reason not to preserve order. I think its a desireable feature (I had actually assumed that it was being preserved) but maybe there was a logic here I'm not aware of. Should I try to fix this?

**Comment by billallen256** [comment]
So we just throw all the packages at pip and let it figure out the order to install (at least the ones that don't have overrides in dependencies.json).  I kind of assumed it was like yum or apt, and that it would just figure it out.  Perhaps that's giving pip too much credit.

Regardless, I don't think pip, or any package manager, can provide guarantees on installation order, simply because of dependencies.  For example, if I say something like: `pip install pymc3 six pandas`, then pandas is still going to get installed before six, because pandas is a dependency of pymc3.

In terms of whether you should fix this, I'm not sure if there's anything to fix.  I guess I'm not understanding why you care what order things are installed.

Alternatively, it's still possible to make multiple calls to ipydeps.pip() to install things in a particular order.  I know that goes against the grain of what you like about being able to pass a list to ipydeps.pip() though.

This also seems related to issue #13 (see my comments there).

**Comment by billallen256** [comment]
A bit more about installation order from the docs, which basically says pip doesn't even provide guarantees on installation order, and any resemblance to the argument order is purely coincidental. https://pip.pypa.io/en/stable/reference/pip_install/#installation-order
