### ISSUE TITLE
ipydeps engages pypki2 setup/prompt when pypki2 is imported

### ISSUE THREAD

**Issue by kafonek** [nbgallery/ipydeps#33]
Originally identified by Rod -- the code below prompts for pki config/pw even when  `~/.config/ipydeps/ipydeps.conf` is empty (i.e. no `--use-pypki2` option).

```python
import ipydeps
import pypki2
ipydeps.pip(module)
```

**Comment by billallen256** [comment]
This one is a bit ugly, since `import pypki2` monkey-patches the libraries that underly `urlopen()`.  The problem seems to stem from `_get_urlopener()`:
https://github.com/nbgallery/ipydeps/blob/0.8.1/ipydeps/__init__.py#L236

Here we see that it's checking whether to return a normal urlopen, or a urlopen with an SSL context provided by pypki2.  However, if the monkey-patch has already been applied by `import pypki2`, then the "normal" urlopen is the one with the SSL context from pypki2 (and all the config/prompting that goes with that).

I'll have to see if there's a good way to have pypki2 provide an unmolested version of urlopen when `--use-pypki2` is not in ipydeps.conf.  In the meantime, here are a couple alternatives...

Alternative 1: Use pypki2config instead to avoid monkey-patching.
https://github.com/nbgallery/pypki2#get-an-sslcontext

Alternative 2: Monkey-patch after you're done with ipydeps.
```
import ipydeps
ipydeps.pip(module)
import pypki2
```

**Comment by billallen256** [comment]
I think the resolution to this one is to simply `import pypki2config` instead.  Ideally ipydeps will move to pypki3, which doesn't even offer a monkey-patching option.
